Update README.md
gliff-ai/document pull request #39
Opened 2022-03-23 16:15 UTC by philhallbio

## Description

New wording for local npm install and lint.

2022-03-23 17:11 UTC, ChasNelson1990 requested changes

2022-03-23 17:11 UTC, ChasNelson1990 commented on README.md
> +Run `bundle config set --local path 'vendor/bundle'` to make the bundle install everything locally (so no sudo is required) and install dependenies locally with `bundle install` and npm dependencies
We don't need bundle or ruby at all now :-), just the npm install.

2022-03-23 17:11 UTC, ChasNelson1990 commented on README.md
> +We recommend that you use globbing to lint all markdown files in the project. To do this, please replace the line "lint:md" in the package.json file with "lint:md": "npx markdownlint-cli --ignore nod
Why don't you actually just commit that change?

2022-03-23 17:11 UTC, ChasNelson1990 commented on README.md
> +Once code alterations have been made, please ensure the validity and stability of the code. We recommend using [Docusaurus](https://docusaurus.io/) using command 'npm run build' or 'npm run start' fo
We don't recommend using docusaurus.... we do use docusaurus lol.

2022-03-30 14:31 UTC, joshuajames-smith requested changes
One other small change I think we also need to make is on line 7.
Currently is:
```
This repository contains the Open Source code for [gliff.ai](https://gliff.ai)’s DOCUMENT supporting library (built using the [Just The Docs](https://pmarsceill.github.io/just-the-docs/) Jekyll template).
```

Change it to:
```
This repository contains the Open Source code for [gliff.ai](https://gliff.ai)’s DOCUMENT supporting library (built using [Docusaurus](https://docusaurus.io)).
```

Otherwise, I think this is good to go once changes are made!

2022-06-10 09:56 UTC, joshuajames-smith approved these changes

2022-06-13 13:13 UTC, ChasNelson1990 approved these changes

2022-06-13 13:13 UTC, merged